require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-capybara
AllCops:
  TargetRubyVersion: 3.1.3
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable
Style/Documentation:
  Enabled: False
